### PR TITLE
Testing React calulcator

### PR DESCRIPTION
**Pull request by SamroodAli**
I have done extensive testing of all the components and logic files.
- [x] All components have snapshot tests
- [x] All component's returning react node are testing using jest test IDs 
- [x] Mock functions have been used for the onClick to separate props recieved from other components
- [x] Screen tests for the final result display component
- [x] User click test for the calculator buttons
Please review my test suite. Thank you for your time and consideration

### CODE REVIEW

**Review by rindrajosia — CHANGES_REQUESTED** [review]
Hi, 

Good job so far!
There are some issues to revise before continuing to the next project but hang in there and read the comments below with care. You can do it! :muscle:


## Required Changes ♻️

- [ ] I got errors related to proptype when I perform an operation. It will be nice if you fix it


- [ ] There should be snapshot tests that check if the main components, at least `Home`, `Calculator`, and `Quote`, from Math Magicians mockups are displayed.
- [ ] There are two ways to make test units. Please add negative test to your APP.
- [ ] The MIT link in your readme is broken. Please fix it. Keep in mind that your readme file is the first thing users check.

_Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------

**Comment by SamroodAli** [comment]
Implemented all changes required
- [ ] Added Home and Quote pages 
- [ ]  Extensive tests written including snapshot tests
- [ ] Fixed Readme link for license
- [ ] Added negative test cases

**Review by e71az — APPROVED** [review]
## Status:  Approved 🟢

Hi, @SamroodAli, 

Your app design got improved by a 1000%, great job with it, it looks amazing now 💯 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

**Comment by SamroodAli** [comment]
Thanks, @e71az @rindrajosia for reviewing my code. I appreciate your time and consideration :100:

**Pull request merged**
